version: 2.1

jobs:
  capture_screenshots:
    parameters:
      config_name:
        type: string
    machine:
      image: 'windows-server-2019-vs2019:stable'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install Python 3.11 (via Chocolatey)
          shell: powershell
          command: |
            choco install -y python --version=3.11.6
            refreshenv
            python --version

      - run:
          name: Install dependencies
          command: |   
            pip install undetected_chromedriver selenium chromedriver_autoinstaller pyautogui fake-useragent requests setuptools distlib
      - run:
          name: Run main with timeout (6 minutes)
          shell: powershell
          command: |
            python videzz_video.py   

workflows:
  version: 2
  parallel_screenshots:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              config_name:
                - test_case_1
                - test_case_2
                - test_case_3
                - test_case_4
                - test_case_5

                
